<?php

namespace App\Livewire\Admin;

use Livewire\Component;
use App\Models\Category;
use Livewire\Attributes\Rule;
use Livewire\Attributes\Layout;

class CategoryCreate extends Component
{
    #[Rule('required|min:3|unique:categories,name')]
    public $name = '';

    public function save()
    {
        // Validate the input
        $this->validate();

        // Create the category (slug will be auto-generated by the package)
        Category::create([
            'name' => $this->name,
        ]);

        // Reset the form field
        $this->reset('name');

        // Emit an event to notify the parent component (optional)
        $this->dispatch('category-created');

        // Show a success message (optional)
        session()->flash('message', 'Category created successfully.');
    }

    #[Layout('components.layouts.admin')]
    public function render()
    {
        return view('livewire.admin.category-create');
    }
}